singleQuote: true
semi: true
tabWidth: 2
printWidth: 80
useTabs: false
trailingComma: es5
bracketSpacing: true
arrowParens: always
quoteProps: consistent
endOfLine: lf
htmlWhitespaceSensitivity: ignore
singleAttributePerLine: true
vueIndentScriptAndStyle: true
insertFinalNewline: true
jsxBracketSameLine: false
overrides:
  - files: "*.ts"
    options:
      parser: typescript
      trailingComma: all
  - files: "*.tsx"
    options:
      parser: typescript
      trailingComma: all
      jsxBracketSameLine: false
  - files: "*.json"
    options:
      parser: json
      trailingComma: none
  - files: "*.yml"
    options:
      parser: yaml
      singleQuote: false
      trailingComma: none
  - files: "*.md"
    options:
      singleQuote: false
      trailingComma: none
