groups:
  - name: cloudflared.rules
    rules:
      - alert: CloudflaredDown
        expr: probe_success{job="Blackbox HTTP-HTTPS", instance=~".*cloudflared.*"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Cloudflared ist nicht erreichbar"
          description: "Der Service Cloudflared ist seit mehr als 1 Minute nicht erreichbar."
