---
Munir:
  name: Munir Mardinli
  description: Homelab enthusiast with a passion for Docker, automation, and modern DevOps practices.
  avatar: https://gitlab.com/uploads/-/system/user/avatar/20932020/avatar.png?width=800
  url: https://github.com/munirmardinli
  location: Germany
  role: Admin & DevOps Architect
  email: munir@mardinli.de
  github: https://github.com/munirmardinli
  gitlab: https://gitlab.com/munirmardinli
  twitter: https://x.com/munirmardinli
  website: https://linktr.ee/munirmardinli

Admin:
  name: Munir Mardinli
  description: Admin the page
  avatar: https://gitlab.com/uploads/-/system/user/avatar/20932020/avatar.png?width=800
  url: https://github.com/munirmardinli
