FROM node:22-alpine AS builder

WORKDIR /home/node/app

COPY package.json package-lock.json tsconfig.json dotenv.d.ts ./
COPY config/tsconfig.base.json ./config/tsconfig.base.json
COPY src ./src
RUN npm install

RUN npx tsc && \
    npm prune --production

FROM node:22-alpine

WORKDIR /home/node/app

COPY --from=builder --chown=node:node /home/node/app/package.json .
COPY --from=builder --chown=node:node /home/node/app/node_modules ./node_modules
COPY --from=builder --chown=node:node /home/node/app/lib ./lib

RUN apk add --no-cache openssh-client sshpass

USER node

CMD ["sh", "-c", "node lib/index.js session"]
