services:
  homelab-cli-dev:
    image: node:22-alpine
    container_name: homelab-cli-dev
    user: root
    command: sh -c "apk add --no-cache openssh-client && node lib/index.js -- setup"
    working_dir: /home/node/app
    env_file: .env
    volumes:
      - ./node_modules:/home/node/app/node_modules
      - ./lib:/home/node/app/lib
      - ./package-lock.json:/home/node/app/package-lock.json
      - ./package.json:/home/node/app/package.json
