FROM node:22-alpine AS builder

WORKDIR /home/node/app

COPY package.json ./
COPY package-lock.json ./

RUN npm ci

COPY src ./src
COPY config ./config
COPY dotenv.d.ts tsconfig.json ./
RUN npx tsc && \
    npm prune --production

FROM node:22-alpine

WORKDIR /home/node/app

COPY --from=builder --chown=node:node /home/node/app/package.json .
COPY --from=builder --chown=node:node /home/node/app/package-lock.json .
COPY --from=builder --chown=node:node /home/node/app/node_modules ./node_modules
COPY --from=builder --chown=node:node /home/node/app/lib ./lib

USER node

CMD ["node", "lib/index.js -- setup"]
