import globals from 'globals';

export default [
  {
    files: ['**/*.js'],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: 'module',
      globals: {
        ...globals.node,
      },
    },
    rules: {
      'no-undef': 'error',
      'no-unused-vars': 'error',
      'no-console': 'off',
      'no-debugger': 'warn',
      'quotes': ['error', 'single'],
      'semi': ['error', 'always'],
      'linebreak-style': ['error', 'unix'],
      'camelcase': [
        'error',
        {
          properties: 'always',
        },
      ],
      'eqeqeq': ['error', 'smart'],
      'no-multi-spaces': 'error',
      'no-multiple-empty-lines': ['error', { max: 1, maxEOF: 0 }],
      'no-trailing-spaces': 'error',
      'no-underscore-dangle': ['error', { allow: ['_id', '_key'] }],
      'no-param-reassign': ['error', { props: false }],
      'no-useless-escape': 'error',
      'no-useless-return': 'error',
      'no-useless-concat': 'error',
      'consistent-return': 'warn',
      'no-implicit-coercion': 'error',
      'no-implicit-globals': 'error',
      'no-invalid-this': 'error',
      'no-multi-assign': 'error',
      'array-callback-return': 'error',
      'curly': 'error',
      'default-case': 'error',
      'dot-notation': 'error',
      'no-alert': 'error',
      'no-caller': 'error',
      'no-empty-function': 'error',
      'no-floating-decimal': 'error',
      'no-implied-eval': 'error',
      'no-labels': 'error',
      'no-lone-blocks': 'error',
      'no-new-func': 'error',
      'no-new-wrappers': 'error',
      'no-octal': 'error',
      'no-redeclare': 'error',
      'no-script-url': 'error',
      'no-sequences': 'error',
      'no-void': 'error',
      'radix': 'error',
      'yoda': 'error',
      'max-params': ['warn', 4],
      'max-lines': ['warn', 700],
      'max-lines-per-function': ['warn', 50],
      'complexity': ['warn', 10],
    },
  },
];
