---
authors:
  Munir:
    name: Munir Mardinli
    description: Homelab enthusiast with a passion for Docker, automation, and modern DevOps practices.
    avatar: https://avatars.githubusercontent.com/u/187268547?v=4
    url: https://github.com/munirmardinli
    slug: munirmardinli

  Admin:
    name: Munir Mardinli
    description: Admin the page
    avatar: https://avatars.githubusercontent.com/u/187268547?v=4
    url: https://github.com/munirmardinli
    slug: munirmardinli
