#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

git pull

echo "Check npm dependencies... "
npm i
echo "Checking TypeScript errors..."
npm ecex tsc --noEmit
echo "Building Project..."
npm ecex tsc
