name: gitStream workflow automation
run-name: |
  /:\ gitStream: PR #${{ fromJSON(fromJSON(github.event.inputs.client_payload)).pullRequestNumber }} from ${{ github.event.inputs.full_repository }}

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

manifest:
  version: 1.0

review_team:
  - Munir Mardinli

sensitive:
  - src/utils/cli.ts
  - src/utils/file.ts
  - src/utils/ssh.ts

config:
  ignore_files:
    - package-lock.json

long_review_threshold: 5

automations:
  explain_code_experts:
    if:
      - true
    run:
      - action: explain-code-experts@v1
        args:
          gt: 10

  approve_safe_changes:
    if:
      - { { is.safe_change } }
    run:
      - action: approve@v1
      - action: add-comment@v1
        args:
          comment: |
            Diese PR wurde als sicher erkannt und automatisch genehmigt.

  require_one_review:
    if:
      - { { not has.sensitive_files } }
      - { { is.quick_review } }
      - { { approvals.zero } }
    run:
      - action: add-reviewers@v1
        args:
          reviewers: [{ { review_team } }]
          unless_reviewers_set: true
      - action: set-required-approvals@v1
        args:
          approvals: 1

  require_two_reviews:
    if:
      - { { is.long_review or has.sensitive_files } }
      - { { approvals.ltTwo } }
    run:
      - action: add-reviewers@v1
        args:
          reviewers: [{ { review_team } }]
          unless_reviewers_set: true
      - action: set-required-approvals@v1
        args:
          approvals: 2

  flag_quick_review_merge:
    if:
      - { { not has.sensitive_files } }
      - { { is.quick_review } }
      - { { not has.do_not_merge_label } }
      - { { approvals.gtZero } }
    run:
      - action: add-comment@v1
        args:
          comment: |
            Diese PR ist bereit zum Mergen! ✌️

  flag_large_review_merge:
    if:
      - { { is.long_review or has.sensitive_files } }
      - { { approvals.gtOne } }
    run:
      - action: add-comment@v1
        args:
          comment: |
            Diese größere PR ist bereit zum Mergen! ✌️

# +----------------------------------------------------------------------------+
# | Custom Expressions                                                         |
# | https://docs.gitstream.cm/how-it-works/#custom-expressions                 |
# +----------------------------------------------------------------------------+

# https://docs.gitstream.cm/filter-functions/#estimatedreviewtime
calc:
  etr: { { branch | estimatedReviewTime } }

has:
  sensitive_files: { { files | match(list=sensitive) | some } }
  do_not_merge_label: { { pr.labels | match(term='Do not merge') | some } }

is:
  safe_change:
    {
      {
        (source.diff.files | isFormattingChange) or (files | allDocs) or (files | allTests) or (files | allImages)
      }
    }
  quick_review:
    { { files | length <= 7 and calc.etr <= long_review_threshold } }
  long_review: { { files | length > 7 or calc.etr > long_review_threshold } }

approvals:
  zero: { { pr.approvals | length == 0 } }
  gtZero: { { pr.approvals | length > 0 } }
  gtOne: { { pr.approvals | length > 1 } }
  ltTwo: { { pr.approvals | length < 2 } }

colors:
  red: b60205
  orange: d93f0b
  yellow: fbca04
  green: 0e8a16
  blue: 1d76db
  purple: 5319e7
