# trunk-ignore(yamllint/quoted-strings)
name: "Pull Request Labeler"

on:
  pull_request_target:

jobs:
  label:
    # trunk-ignore(checkov/CKV2_GHA_1)
    permissions:
      contents: read
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
